repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: check-yaml
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
-   repo: https://github.com/psf/black
    rev: "25.9.0"
    hooks:
    - id: black
-   repo: https://github.com/pycqa/isort
    rev: "7.0.0"
    hooks:
      - id: isort
        name: isort (python)
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: "v0.14.1"
    hooks:
    -   id: ruff
- repo: local
  hooks:
    - id: cargo-fmt
      name: cargo fmt (rust))
      entry: bash -lc 'rustup component add rustfmt >/dev/null 2>&1 || true; cargo fmt --all --'
      language: system
      files: '\.rs$'
    - id: cargo-fix
      name: cargo fix (rust)
      entry: bash -lc 'cargo fix --all --allow-dirty --allow-staged'
      language: system
      files: '\.rs$'
    # - id: cargo-clippy
    #   name: cargo clippy (rust) (optional)
    #   entry: bash -lc 'rustup component add clippy >/dev/null 2>&1 || true; cargo clippy --all -- -D warnings'
    #   language: system
    #   files: '\.rs$'
- repo: https://github.com/PyCQA/docformatter
  rev: v1.7.7
  hooks:
    - id: docformatter
      name: docformatter
      entry: docformatter
      language: python
      types: [python]
      additional_dependencies: [tomli]
      args: [--in-place, --config, ./pyproject.toml]
