name: "PR lint: changelog + version bump"
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  check-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # Enforce changelog updated: custom from https://github.com/tarides/changelog-check-action/blob/main/action.yml to run locally in act
      - name: Check changelog updated
        run: |
          set -euo pipefail
          git remote set-url origin "https://github.com/remydubois/illico.git"
          git fetch origin main --depth=1
          if git diff --quiet "origin/main" -- changelog.md; then
            echo "Error: changelog.md was not updated!"
            exit 1
          fi

          echo "changelog.md was updated."

      # Enforce version bump in pyproject.toml
      - name: Verify version bump in pyproject.toml
        id: verify
        run: |
          git remote set-url origin "https://github.com/remydubois/illico.git"
          git fetch origin main --depth=1
          BASE_VERSION=$(git show origin/main:pyproject.toml \
            | grep '^version' | head -n1 | sed 's/.*= *//; s/"//g')
          HEAD_VERSION=$(grep '^version' pyproject.toml \
            | head -n1 | sed 's/.*= *//; s/"//g')

          echo "Base version: $BASE_VERSION"
          echo "Head version: $HEAD_VERSION"

          if [ "$BASE_VERSION" = "$HEAD_VERSION" ]; then
            echo "Error: version was not bumped!"
            exit 1
          fi
