name: Python package

on:
  # push:
  #   branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  format-check:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    steps:
    - uses: actions/checkout@v6
    - uses: actions-rust-lang/setup-rust-toolchain@v2
      with:
        components: rustfmt
    - name: Set up Python
      uses: actions/setup-python@v7
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        python -m pip install ruff -q
    - name: Lint with ruff
      run: |
        ruff check .
        ruff format --check .
    - name: cargo formatter
      run: |
        cargo fmt -- --check
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
        dev-extra: ["dev", "dev-no-dask"]
    steps:
    - uses: actions/checkout@v6
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v7
      with:
        python-version: ${{ matrix.python-version }}
    - uses: actions-rust-lang/setup-rust-toolchain@v2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade poetry -q
        poetry env use $(which python)
        poetry install --with ${{ matrix.dev-extra }} -q
        python -m pip install maturin
    - name: Compile Rust backend
      run: |
        poetry run maturin develop --release
    - name: Test with pytest (no tox because matrix already handles python version)
      env:
        ILLICO_DEV_GROUP: ${{ matrix.dev-extra }}
      run: |
        poetry run pytest -m "not speed_bench and not memory_bench" -x
